### ISSUE TITLE
Add another way to generate mazes with position selectors

### ISSUE THREAD

**Issue by Panda843** [Panda843/Maze#1]
That way the player will not have to worry about the size of a maze. Something like :

/maze pos1, 
/maze pos2, 
/maze <block_id[:block_meta]>

**Comment by ZPlayzMCPE** [comment]
Why are you commenting on yourself? xD

**Comment by Panda843** [comment]
Right now if you generate a maze, the middle of the maze will be at the coordinates where you generated it in the first place. (Please keep that in mind when generating a maze)

With position selectors it will be easier to choose the start/end points of the maze (including its height) but this method also has disadvantages. For example, you will have to go to two locations and type the /maze command with the needed arguments three times . It is more annoying but as I said above, it is an easier way to choose precisely the start/end points of the maze.

**Comment by TheFixerDevelopment** [comment]
There's no need to reply to yourself, it's completely stupid in my opinion. Just get a note book or something and write it there.

**Comment by Panda843** [comment]
By your logic we can ask ourselves why you need to create milestones on github... clearly you don't get how things work

**Comment by Panda843** [comment]
it is completely normal to create issues on your own projects regarding bugs or improvements. That way others will know what is next and will also be able to help... Why do you think the lead developer of PMMP does the same? Think a bit when posting

https://github.com/pmmp/PocketMine-MP/issues/1299
https://github.com/pmmp/PocketMine-MP/issues/1300

**Comment by Panda843** [comment]
I mean, I am not much of a professional as well, but if you don't know how something works, keep your opinion to yourself
